export const ProviderCapability = {
  AUTH: 'AUTH',
  CATALOG_SYNC: 'CATALOG_SYNC',
  PLAN_SYNC: 'PLAN_SYNC',
  PURCHASE: 'PURCHASE',
  ESIM: 'ESIM',
  TOP_UP: 'TOP_UP',
  USAGE: 'USAGE',
  STATUS: 'STATUS',
  SUSPEND: 'SUSPEND',
  RESUME: 'RESUME',
  CANCEL: 'CANCEL',
  WEBHOOKS: 'WEBHOOKS',
  SMS_MT: 'SMS_MT',
  SMS_MO: 'SMS_MO',
  WALLET: 'WALLET',
  INVENTORY: 'INVENTORY',
  PCR_PROFILE: 'PCR_PROFILE',
  BALANCE: 'BALANCE',
  CREATE_BUNDLE: 'CREATE_BUNDLE',
  UPDATE_BUNDLE: 'UPDATE_BUNDLE',
  LIST_BUNDLES: 'LIST_BUNDLES',
  NON_POOL_PURCHASE: 'NON_POOL_PURCHASE',
  DIRECT_IMSI_CREATE: 'DIRECT_IMSI_CREATE',
  EVENT_LOGS: 'EVENT_LOGS',
  RATE_LIST: 'RATE_LIST',
  /**
   * Provider-side custom offering/template creation (e.g. Telna POST
   * /v2.1/pcr/package-templates). Provider-neutral capability: a connector that
   * truthfully implements createCustomPackage() declares this. Never enabled
   * merely because a documented endpoint exists.
   */
  CUSTOM_PACKAGE_CREATION: 'CUSTOM_PACKAGE_CREATION',
} as const

export type ProviderCapability = (typeof ProviderCapability)[keyof typeof ProviderCapability]

export const CAPABILITY_LABELS: Record<ProviderCapability, string> = {
  AUTH: 'Authentication',
  CATALOG_SYNC: 'Catalog Sync',
  PLAN_SYNC: 'Plan Sync',
  PURCHASE: 'Purchase',
  ESIM: 'eSIM',
  TOP_UP: 'Top-Up',
  USAGE: 'Usage',
  STATUS: 'Status',
  SUSPEND: 'Suspend',
  RESUME: 'Resume',
  CANCEL: 'Cancel',
  WEBHOOKS: 'Webhooks',
  SMS_MT: 'SMS (Outbound)',
  SMS_MO: 'SMS (Inbound)',
  WALLET: 'Wallet',
  INVENTORY: 'Inventory',
  PCR_PROFILE: 'PCR Profile',
  BALANCE: 'Balance',
  CREATE_BUNDLE: 'Create Bundle',
  UPDATE_BUNDLE: 'Update Bundle',
  LIST_BUNDLES: 'List Bundles',
  NON_POOL_PURCHASE: 'Non-Pool Purchase',
  DIRECT_IMSI_CREATE: 'Direct IMSI Create',
  EVENT_LOGS: 'Event Logs',
  RATE_LIST: 'Rate List',
  CUSTOM_PACKAGE_CREATION: 'Custom Package Creation',
}

export const CAPABILITY_COLORS: Record<ProviderCapability, string> = {
  AUTH: 'bg-blue-100 text-blue-700',
  CATALOG_SYNC: 'bg-emerald-100 text-emerald-700',
  PLAN_SYNC: 'bg-indigo-100 text-indigo-700',
  PURCHASE: 'bg-cyan-100 text-cyan-700',
  ESIM: 'bg-teal-100 text-teal-700',
  TOP_UP: 'bg-purple-100 text-purple-700',
  USAGE: 'bg-amber-100 text-amber-700',
  STATUS: 'bg-teal-100 text-teal-700',
  SUSPEND: 'bg-orange-100 text-orange-700',
  RESUME: 'bg-lime-100 text-lime-700',
  CANCEL: 'bg-red-100 text-red-700',
  WEBHOOKS: 'bg-indigo-100 text-indigo-700',
  SMS_MT: 'bg-pink-100 text-pink-700',
  SMS_MO: 'bg-rose-100 text-rose-700',
  WALLET: 'bg-green-100 text-green-700',
  INVENTORY: 'bg-gray-100 text-gray-700',
  PCR_PROFILE: 'bg-violet-100 text-violet-700',
  BALANCE: 'bg-sky-100 text-sky-700',
  CREATE_BUNDLE: 'bg-emerald-100 text-emerald-700',
  UPDATE_BUNDLE: 'bg-cyan-100 text-cyan-700',
  LIST_BUNDLES: 'bg-blue-100 text-blue-700',
  NON_POOL_PURCHASE: 'bg-gray-100 text-gray-700',
  DIRECT_IMSI_CREATE: 'bg-gray-100 text-gray-700',
  EVENT_LOGS: 'bg-violet-100 text-violet-700',
  RATE_LIST: 'bg-amber-100 text-amber-700',
  CUSTOM_PACKAGE_CREATION: 'bg-indigo-100 text-indigo-700',
}
